### ISSUE TITLE
set_muted removes attributes from prosody

### ISSUE THREAD

**Issue by teowoz** [avstack/gst-meet#16]
Calling conference.set_muted (introduced in d37e05b) removes nick (and probably other attributes, too) from user information stored by prosody.

We use this script: https://community.jitsi.org/t/jitsi-monitoring-mod-room-list-occupant-list/31191 for accessing participant list from non-Jitsi services. We use gst-meet for receiving media. gst-meet's nick appears as empty in participant list. After commenting out ```conference.set_muted``` in ```main.rs``` gst-meet's nick is displayed correctly.

The problem is caused by ```set_muted``` sending presence tag containing only ```videomuted``` or ```audiomuted``` tag, so the whole object is overwritten within prosody. On the other hand, Jitsi Meet frontend sends the whole object (containing nick, video codec etc) on every mute/unmute.

A quick workaround is to revert d37e05b. To keep the functionality, gst-meet would need to:
* set videomuted and audiomuted to correct values [when it sends the presence tag for the first time](https://github.com/avstack/gst-meet/blob/e8a6f4dc16314f6c04e9abd6358a27d8998f4beb/lib-gst-meet/src/conference.rs#L454) and not use the ```set_muted``` function, OR
* send all tags in ```set_muted```

**Comment by jbg** [comment]
@teowoz #18 should fix this, please test!

**Comment by teowoz** [comment]
It works. The gst-meet participant is shown in GUI with muted mic and disabled camera icons and the participant nick is accessible from Prosody Lua script.

Thanks!
