### ISSUE TITLE
Self signed certificate

### ISSUE THREAD

**Issue by alesovmed** [avstack/gst-meet#21]
This is a continuation of Issue #7 .
The problem seems to persist also in the latest master. Error prints are exactly the same as in #7 .
The gst-meet version is the same as in #7:  $gst-meet --version
gst-meet 0.2.2
  Perhaps there is some new option that should be invoked in run-time or during build process for using self-signed certificates?
Which logging option should be enabled to further debug this issue ?
(E.g. wscat has "--no-check" runtime option and browsers optionally require adding an exception.)

**Comment by jbg** [comment]
Are you sure the error message is exactly the same? (`invalid certificate: BadDER`)

That would suggest rustls is still being used

**Comment by alesovmed** [comment]
Yes, I'm sure that the error message is the same.

**Comment by jbg** [comment]
Can you please confirm:
 * Which version of gst-meet you are using (if you checked it out from git, the exact git commit hash obtained by `git rev-parse HEAD`)
 * How you are building gst-meet (the exact command you are using)
 * The exact error message (please copy-paste it, don't paraphrase it)

**Comment by alesovmed** [comment]
Version:
$git rev-parse HEAD
6b33952074ce32250c7cea094637faf10758722a

Command:
$ cargo install --force gst-meet

Error message:
$ gst-meet -v --web-socket-url=wss://meet.iskratel.build/xmpp-websocket          --xmpp-domain=meet.iskratel.build          --room-name=qay1          --send-pipeline="autovideosrc ! queue ! videoconvert ! vp8enc buffer-size=1000 deadline=1 name=video
                          autoaudiosrc ! queue ! audioconvert ! audioresample ! opusenc name=audio"          --recv-pipeline-participant-template="opusdec name=audio ! autoaudiosink
                                               vp8dec name=video ! videoconvert ! autovideosink"
Nov 22 15:58:40.721  INFO Connecting XMPP WebSocket to wss://meet.iskratel.build/xmpp-websocket
Nov 22 15:58:40.722 DEBUG No cached session for DNSNameRef("meet.iskratel.build")    
Nov 22 15:58:40.722 DEBUG Not resuming any session    
Nov 22 15:58:40.724 DEBUG Using ciphersuite TLS13_CHACHA20_POLY1305_SHA256    
Nov 22 15:58:40.724 DEBUG Not resuming    
Nov 22 15:58:40.724 DEBUG TLS1.3 encrypted extensions: [ServerNameAck]    
Nov 22 15:58:40.724 DEBUG ALPN protocol is None    
Nov 22 15:58:40.724  WARN Sending fatal alert DecodeError    
Error: IO error: invalid certificate: BadDER

Caused by:
    invalid certificate: BadDER
$

**Comment by jbg** [comment]
Thanks so much for the info.

There hasn't been a new release since I made the changes mentioned in the previous ticket, so rather than using `cargo install`, you'll have to run it like this:

```sh
git clone https://github.com/avstack/gst-meet.git
cd gst-meet
cargo run --release -- # add your gst-meet options here
```

I'll leave this ticket open for now as a reminder that I need to make a new release, just waiting for a couple more changes to land first.

**Comment by alesovmed** [comment]
Thank you for the hint. Now the error looks like that could be overridden, perhaps with some run-time option ?
(e.g. wscat has "--no-check" runtime option and browsers optionally require adding an exception.)

$ target/release/gst-meet -v --web-socket-url=wss://meet.iskratel.build/xmpp-websocket          --xmpp-domain=meet.iskratel.build          --room-name=qay1          --send-pipeline="autovideosrc ! queue ! videoconvert ! vp8enc buffer-size=1000 deadline=1 name=video
                          autoaudiosrc ! queue ! audioconvert ! audioresample ! opusenc name=audio"          --recv-pipeline-participant-template="opusdec name=audio ! autoaudiosink
                                               vp8dec name=video ! videoconvert ! autovideosink"
Nov 24 13:00:05.280  INFO Connecting XMPP WebSocket to wss://meet.iskratel.build/xmpp-websocket
Error: failed to connect

Caused by:
    0: failed to connect XMPP WebSocket
    1: TLS error: native-tls error: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1913: (self signed certificate)
    2: native-tls error: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1913: (self signed certificate)
    3: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1913: (self signed certificate)
    4: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1913:
$

**Comment by jbg** [comment]
You should be able to use a self-signed certificate now by *both*:

1. building with the `tls-insecure` feature (e.g. `cargo build --features tls-insecure`), *and*
2. passing `--tls-insecure` to `gst-meet`.
