### ISSUE TITLE
can't show video in the jitsi meet 

### ISSUE THREAD

**Issue by zsinba** [avstack/gst-meet#27]
docker run -d bgcloud/gst-meet:v1.0  --web-socket-url=wss://xxxxxxxxxxxxx/xmpp-websocket --xmpp-domain=xxxxxxxxxxxxxxx  --room-name=test  --send-pipeline="rtmpsrc  location=rtmp://xxxxxxxxxxx.com:19350/yuanjin/SND005 ! queue ! matroskademux name=demuxer demuxer.video_0 ! queue name=video demuxer.audio_0 ! queue ! vorbisdec ! audioconvert ! audioresample ! opusenc name=audio"

I can compile the docker images and run it.
but the result page didn't show the vidoe.

I am sure the RTMP URL and jitsi is ok.

![image](https://user-images.githubusercontent.com/890157/146188279-19ea7529-505f-43a5-b790-7b2d76fd5337.png)

**Comment by jbg** [comment]
Please, don't use our GitHub issues for general support & learning to use GStreamer. We don't have time to do one-on-one tutorials. The issues are for bugs & feature requests. You can use GitHub Discussions, or the GStreamer community (forums, IRC etc) to learn to use GStreamer, do a web search for GStreamer tutorials, or use the GStreamer documentation.

Your GStreamer pipeline is incorrect, it makes no sense to link `rtmpsrc` to `matroskademux`. If you follow the [instructions for debugging your GStreamer pipeline](https://github.com/avstack/gst-meet#debugging) in the README, you'll find some errors from GStreamer although they can be quite cryptic at times.
