### ISSUE TITLE
Release new versions of packages on crates.io

### ISSUE THREAD

**Issue by jbg** [avstack/gst-meet#34]
A new release is currently blocked by the released version of `xmpp-parsers` (0.18.1) not building:

```
error[E0277]: the trait bound `BareJid: IntoAttributeValue` is not satisfied
    --> .cargo/registry/src/github.com-1ecc6299db9ec823/xmpp-parsers-0.18.1/src/util/macros.rs:697:39
     |
697  |                       builder = builder.attr($attr_name, elem.$attr);
     |                                         ^^^^ the trait `IntoAttributeValue` is not implemented for `BareJid`
     |
    ::: .cargo/registry/src/github.com-1ecc6299db9ec823/xmpp-parsers-0.18.1/src/mix.rs:117:1
     |
117  | / generate_element!(
118  | |     /// Update a given subscription.
119  | |     UpdateSubscription, "update-subscription", MIX_CORE,
120  | |     attributes: [
...    |
130  | |     ]
131  | | );
     | |_- in this macro invocation
     |
     = note: required because of the requirements on the impl of `IntoAttributeValue` for `Option<BareJid>`
```

I've been using a git dependency (the problem doesn't exist in the latest code on gitlab, only in the released version), but can't release to crates.io with a git dependency. Any chance of a new `xmpp-parsers` release @linkmauve?

**Comment by linkmauve** [comment]
Oh yes sure, I even added an extdisco module so you can drop your version and use the standard one.  In the future, feel free to poke us whenever you want a release, numbers are cheap. :)

**Comment by jbg** [comment]
Done in d9642aa7603856269d4b766f07dc3ff23e04c668

**Comment by jbg** [comment]
Filed #35 as follow-up work to replace our extdisco code with the xmpp-parsers module.
