### ISSUE TITLE
cannot resolve apk.avstack.net

### ISSUE THREAD

**Issue by chunsan** [avstack/gst-meet#51]
hello
I'm using Dockerfile to build a docker image, but  cannot download this file.Here is the error code:
**Could not resolve host: apk.avstack.net**
Is the website still working? Thanks a lot.

**Comment by jbg** [comment]
Thank you for the report — the private APK repository is no longer needed since GStreamer 1.20 was released and packaged in Alpine, but it looks like the new Dockerfile hasn't been published. You can remove the relevant references from the Dockerfile in the meantime — we'll publish a new one soon.
