### ISSUE TITLE
Not able to compile

### ISSUE THREAD

**Issue by roshanprince402** [avstack/gst-meet#59]
Getting error when compiling.
 OS Debian 11
GStreamer v1.20.4

![image](https://user-images.githubusercontent.com/29180121/206710980-91d4fcc9-a38c-4021-9246-abe2a6836522.png)

**Comment by lorenapre** [comment]
just in case it is useful for you https://github.com/avstack/gst-meet/discussions/68

**Comment by danryu** [comment]
@roshanprince402  If you update to gst-meet 0.4.2 and lib-gst-meet 0.7.0 you should find this build error has gone.
(If you build from `master` you will get the build error that @lorenapre links to, I think!)

**Comment by lorenapre** [comment]
I think it could be the same error in both cases.

I had to change in jitsi-xmpp-parsers/src/jingle_ssma.rs ´´´use xmpp_parsers::´´´ to ´´´pub use xmpp_parsers::´´´

**Comment by jbg** [comment]
Fixed in master.
