### ISSUE TITLE
Do I need a specific version of prosody/jitsi?

### ISSUE THREAD

**Issue by lorenapre** [avstack/gst-meet#70]
Hey guys, again me, sorry.  Just a little question, do I need a specific version of prosody/jitsi to make work this?  

Additional data:
I was seeing that the execution is waiting forever in the rx.await (before Ok(conference)) in conference.rs (line 245 approx).

**Comment by jbg** [comment]
The code in `master` is now tested and working with the latest Jitsi Meet release `8615`. It may also work with other recent releases, but has not (yet) been tested with them.
